=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/base.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.issuetracker.training.org/base" 
		xmlns:d4="http://www.issuetracker.training.org/base" elementFormDefault="qualified">
		
    	<element name="base">
    		<complexType>
    			<sequence>
    				<element name="issues" type="d4:Issue"
    					maxOccurs="unbounded" minOccurs="0">
    				</element>
    				<element name="comments">
    					<complexType>
    						<sequence>
    							<element name="id" type="string">
    							</element>
    							<element name="issueId" type="string">
    							</element>
    							<element name="date" type="string">
    							</element>
    							<element name="addedBy" type="string">
    							</element>
    							<element name="addDate" type="string">
    							</element>
    							<element name="comment" type="string">
    							</element>
    						</sequence>
    					</complexType>
    				</element>
    				<element name="attachments" type="d4:Attachment"></element>
    			</sequence>
    		</complexType>
    	</element>

    	<complexType name="Issue">
    		<sequence>
    			<element name="id" type="int"></element>
    			<element name="createDate" type="dateTime"></element>
    			<element name="createBy" type="int"></element>
    			<element name="modifyDate" type="dateTime"></element>
    			<element name="modifyBy" type="int"></element>
    			<element name="summary" type="int"></element>
    			<element name="description" type="int"></element>
    			<element name="status" type="int"></element>
    			<element name="resolution" type="int"></element>
    			<element name="priority" type="int"></element>
    			<element name="type" type="int"></element>
    			<element name="project" type="int"></element>
    			<element name="buildFound" type="int"></element>
    			<element name="assigned" type="int"></element>
    		</sequence>
    	</complexType>


    	<complexType name="Attachment">
    		<sequence>
    			<element name="id" type="string"></element>
    			<element name="issueId" type="string"></element>
    			<element name="link" type="string"></element>
    		</sequence>
    	</complexType>
</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/base.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:base xmlns:d4="http://www.issuetracker.training.org/base" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.issuetracker.training.org/base base.xsd ">
  <d4:issues>
    <d4:id>0</d4:id>
    <d4:createDate>2001-12-31T12:00:00</d4:createDate>
    <d4:createBy>0</d4:createBy>
    <d4:modifyDate>2001-12-31T12:00:00</d4:modifyDate>
    <d4:modifyBy>0</d4:modifyBy>
    <d4:summary>0</d4:summary>
    <d4:description>0</d4:description>
    <d4:status>0</d4:status>
    <d4:resolution>0</d4:resolution>
    <d4:priority>0</d4:priority>
    <d4:type>0</d4:type>
    <d4:project>0</d4:project>
    <d4:buildFound>0</d4:buildFound>
    <d4:assigned>0</d4:assigned>
  </d4:issues>
  <d4:comments>
    <d4:id>d4:id</d4:id>
    <d4:issueId>d4:issueId</d4:issueId>
    <d4:date>d4:date</d4:date>
    <d4:addedBy>d4:addedBy</d4:addedBy>
    <d4:addDate>d4:addDate</d4:addDate>
    <d4:comment>d4:comment</d4:comment>
  </d4:comments>
  <d4:attachments>
    <d4:id>d4:id</d4:id>
    <d4:issueId>d4:issueId</d4:issueId>
    <d4:link>d4:link</d4:link>
  </d4:attachments>
</d4:base>
