=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/user.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.issuetracker.training.org/user"
	xmlns:d4="http://www.issuetracker.training.org/user"
	elementFormDefault="qualified">
	<element name="users">
		<complexType>
			<sequence>
				<element name="user" type="d4:User" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<simpleType name="Email">
		<restriction base="string">
			<pattern value="(\d?[a-zA-Z\d\.\\_\-])+@([a-zA-Z\d]+(\.)?)+">
			</pattern>
		</restriction>
	</simpleType>
	<simpleType name="Password">
		<restriction base="string">
			<pattern value="[\w\\_@\-\.\\,][\w\\_@\-\.\\,\\ ]{4,}">
			</pattern>
		</restriction>
	</simpleType>
	<complexType name="TextField">
		<simpleContent>
			<extension base="string">
				<attribute name="id" type="int" use="required" />
			</extension>
		</simpleContent>
	</complexType>
	<complexType name="User">
		<sequence>
			<element name="firstName" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="lastName" type="string" maxOccurs="1"
				minOccurs="1"></element>
			<element name="email" maxOccurs="1" minOccurs="1" type="d4:Email">
			</element>
			<element name="role" maxOccurs="1" minOccurs="1" type="int">
			</element>
			<element name="password" type="d4:Password" maxOccurs="1"
				minOccurs="1"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>
</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:users xmlns:d4="http://www.issuetracker.training.org/user" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.issuetracker.training.org/user user.xsd ">
  <d4:user id="0">
    <d4:firstName>Ivan</d4:firstName>
    <d4:lastName>Sidoroff</d4:lastName>
    <d4:email>sidor@drinkaware.com</d4:email>
    <d4:role>0</d4:role>
    <d4:password>asd111</d4:password>
  </d4:user>
  <d4:user id="1">
    <d4:firstName>Petr</d4:firstName>
    <d4:lastName>Petrov</d4:lastName>
    <d4:email>pp@tut.by</d4:email>
    <d4:role>1</d4:role>
    <d4:password>asd111</d4:password>
  </d4:user>
  <d4:user id="2">
  	<d4:firstName>qwre</d4:firstName>
  	<d4:lastName>wererwe</d4:lastName>
  	<d4:email>qwer@qwer.com</d4:email>
  	<d4:role>0</d4:role>
  	<d4:password>asd123</d4:password>
  </d4:user>
</d4:users>
