=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/base.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.issuetracker.training.org/base"
	xmlns:d4="http://www.issuetracker.training.org/base">

	<element name="base">
		<complexType>
			<sequence>
				<element name="issues" type="d4:Issues" minOccurs="1" maxOccurs="1" />
				<element name="comments" type="d4:Comments" minOccurs="1" maxOccurs="1" />
				<element name="attachments" type="d4:Attachments" minOccurs="1" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Issue">
		<sequence>
			<element name="createDate" type="dateTime"></element>
			<element name="createBy" type="int"></element>
			<element name="modifyDate" type="dateTime"></element>
			<element name="modifyBy" type="int"></element>
			<element name="summary" type="string"></element>
			<element name="description" type="string"></element>
			<element name="status" type="int"></element>
			<element name="resolution" type="int"></element>
			<element name="priority" type="int"></element>
			<element name="type" type="int"></element>
			<element name="project" type="int"></element>
			<element name="buildFound" type="int"></element>
			<element name="assigned" type="int"></element>
		</sequence>
		<attribute name="id" type="int"></attribute>
	</complexType>

	<complexType name="Comment">
		<sequence>
			<element name="id" type="string">
			</element>
			<element name="issueId" type="string">
			</element>
			<element name="date" type="string">
			</element>
			<element name="addedBy" type="string">
			</element>
			<element name="addDate" type="string">
			</element>
			<element name="comment" type="string">
			</element>
		</sequence>
	</complexType>


	<complexType name="Attachment">
		<sequence>
			<element name="id" type="string"></element>
			<element name="issueId" type="string"></element>
			<element name="link" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="Issues">
		<sequence>
			<element name="issue" type="d4:Issue" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Comments">
		<sequence>
			<element name="comment" type="d4:Comment" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Attachments">
		<sequence>
			<element name="attachment" type="d4:Attachment" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/base.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:base xmlns:d4="http://www.issuetracker.training.org/base"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.issuetracker.training.org/base base.xsd ">
	<issues>
		<issue id="0">
			<createDate>2009-11-12T11:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2009-11-12T11:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>set description for the window app</summary>
			<description>need to do to set the variable parameter description of the application window</description>
			<status>2</status>
			<resolution>4</resolution>
			<priority>3</priority>
			<type>3</type>
			<project>0</project>
			<buildFound>1</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="1">
			<createDate>2009-12-12T11:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2009-12-12T11:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>Error loading station with a shortage of object images or colors</summary>
			<description>Error loading station with a shortage of object images or colors</description>
			<status>2</status>
			<resolution>4</resolution>
			<priority>3</priority>
			<type>3</type>
			<project>0</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="2">
			<createDate>2010-01-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2010-02-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>Error loading commands</summary>
			<description>error occurs at the wrong location in the description lines for primary and responsible command</description>
			<status>2</status>
			<resolution>4</resolution>
			<priority>1</priority>
			<type>3</type>
			<project>0</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="3">
			<createDate>2010-01-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2010-02-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>incorrectly parse object 'arrow'</summary>
			<description>Definition of state hands BaseOb :: gxs () - incorrectly recognize arrow which was not in the itinerary, but was controlled by common pulses. Added to the direct control of the field to pass uncontrolled impulses ("op6" = 1).</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>1</priority>
			<type>3</type>
			<project>1</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="4">
			<createDate>2010-02-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2010-03-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>wrong state object 'arrow'</summary>
			<description>definition of the state in the absence of provisions of the arrow (to the right or only burned wit or "pants")</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>2</priority>
			<type>3</type>
			<project>1</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="5">
			<createDate>2010-02-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2010-03-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>improper display the description in the tester</summary>
			<description>The tester has made the possibility of pass-through momentum by pressing the up and down arrows. Changed the text prompts to impulses - now a "block" and "output".</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>4</priority>
			<type>1</type>
			<project>1</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
			<issue id="6">
			<createDate>2010-03-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2010-04-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>log record is not</summary>
			<description>log entry if you can not connect to the CEO - entry is made only if a specify + log.</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>2</priority>
			<type>2</type>
			<project>1</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
			<issue id="7">
			<createDate>2011-03-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2011-04-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>Protocol does not play</summary>
			<description>bug in which the protocol was read only from 2010 year. Now you can read and record in 2011 and in 2012. And then depending on the apocalypse :)</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>2</priority>
			<type>2</type>
			<project>2</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="8">
			<createDate>2011-03-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2011-04-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>error load from config.xml</summary>
			<description>bug when loading from config.xml and an error while loading an annual protocol.</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>2</priority>
			<type>2</type>
			<project>2</project>
			<buildFound>2</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="9">
			<createDate>2011-04-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2011-05-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>does not receive data from serial port</summary>
			<description>IPXDataChannel - incorrectly parse the data in and out of the read cycle.</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>2</priority>
			<type>2</type>
			<project>3</project>
			<buildFound>1</buildFound>
			<assigned>2</assigned>
		</issue>
		<issue id="10">
			<createDate>2011-05-12T08:33:00</createDate>
			<createBy>1</createBy>
			<modifyDate>2011-06-12T14:33:00</modifyDate>
			<modifyBy>1</modifyBy>
			<summary>no description code of the station in the log</summary>
			<description>no description code of the station in the log</description>
			<status>5</status>
			<resolution>1</resolution>
			<priority>2</priority>
			<type>2</type>
			<project>3</project>
			<buildFound>1</buildFound>
			<assigned>2</assigned>
		</issue>
	</issues>
	<comments>
		<comment>
      <id>id</id>
      <issueId>issueId</issueId>
      <date>date</date>
      <addedBy>addedBy</addedBy>
      <addDate>addDate</addDate>
      <comment>comment</comment>
    </comment>
	</comments>
	<attachments>
		<attachment>
			<id>id</id>
			<issueId>issueId</issueId>
			<link>link</link>
		</attachment>
	</attachments>
</d4:base>
