=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/comment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.issuetracker.training.org/base"
	xmlns:d4="http://www.issuetracker.training.org/base">

	<element name="base">
		<complexType>
			<sequence>
				<element name="comments" type="d4:Comments" minOccurs="1" maxOccurs="1" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Comment">
		<sequence>
			<element name="issueId" type="int"></element>
			<element name="addedBy" type="int"></element>
			<element name="addDate" type="dateTime"></element>
			<element name="text" type="string"></element>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>

	<complexType name="Comments">
		<sequence>
			<element name="comment" type="d4:Comment" minOccurs="1"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/comment.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:base xmlns:d4="http://www.issuetracker.training.org/base"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.issuetracker.training.org/base comment.xsd ">
  <comments>
    <comment id="1">
      <issueId>10</issueId>
      <addedBy>0</addedBy>
      <addDate>2002-01-01T12:00:00</addDate>
      <text>comment 1 need to do to set the variable parameter description of the application window need to do to set the variable parameter description of the application window</text>
    </comment>
    <comment id="2">
      <issueId>9</issueId>
      <addedBy>0</addedBy>
      <addDate>2002-12-31T12:00:00</addDate>
      <text>comment 2</text>
    </comment>
    <comment id="3">
      <issueId>10</issueId>
      <addedBy>0</addedBy>
      <addDate>2003-12-31T12:00:00</addDate>
      <text>comment 3</text>
    </comment>
    <comment id="4">
      <issueId>9</issueId>
      <addedBy>0</addedBy>
      <addDate>2004-12-31T12:00:00</addDate>
      <text>comment 4</text>
    </comment>
  </comments>
</d4:base>
