=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.issuetracker.training.org/configuration"
		xmlns:d4="http://www.issuetracker.training.org/configuration"
		xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="configuration">
		<complexType>
			<sequence>
				<element name="statuses" type="d4:Statuses" maxOccurs="1" minOccurs="1"/>
				<element name="resolutions" type="d4:Resolutions" maxOccurs="1" minOccurs="1"/>
				<element name="priorities" type="d4:Priorities" maxOccurs="1" minOccurs="1"/>
				<element name="types" type="d4:Types" maxOccurs="1" minOccurs="1"/>
			</sequence>
		</complexType>
	</element>

	<complexType name="TextField">
		<simpleContent>
			<extension base="string">
				<attribute name="id" type="int" use="required" />
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="Statuses">
		<sequence>
			<element name="status" type="d4:TextField" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="Resolutions">
		<sequence>
			<element name="resolution" type="d4:TextField" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="Priorities">
		<sequence>
			<element name="priority" type="d4:TextField" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="Types">
		<sequence>
			<element name="type" type="d4:TextField" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<simpleType name="UnusedType">
		<annotation>
			<documentation>this item temporary unused</documentation>
		</annotation>
		<restriction base="string">
			<pattern value="[A-Za-z]([ A-Za-z]*)" />
		</restriction>
	</simpleType>
</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:configuration xmlns:d4="http://www.issuetracker.training.org/configuration"
				  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				  xsi:schemaLocation="http://www.issuetracker.training.org/configuration configuration.xsd ">
  <statuses>
    <status id="1">New</status>
    <status id="2">Assigned</status>
    <status id="3">In Progress</status>
    <status id="4">Resolved</status>
    <status id="5">Closed</status>
    <status id="6">Reopened</status>
  </statuses>
  <resolutions>
    <resolution id="1">Fixed</resolution>
    <resolution id="2">Invalid</resolution>
    <resolution id="3">Wontfix</resolution>
    <resolution id="4">Worksforme</resolution>
  </resolutions>
  <priorities>
    <priority id="1">Critical</priority>
    <priority id="2">Major</priority>
    <priority id="3">Important</priority>
    <priority id="4">Minor</priority>
  </priorities>
  <types>
    <type id="1">Cosmetic</type>
    <type id="2">Bug</type>
    <type id="3">Feature</type>
    <type id="4">Performance</type>
  </types>
</d4:configuration>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:configuration xmlns:d4="http://www.issuetracker.training.org/configuration" 
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				 xsi:schemaLocation="http://www.issuetracker.training.org/configuration configuration.xsd ">
  <d4:statuses>
    <d4:status id="1">New</d4:status>
    <d4:status id="2">Assigned</d4:status>
    <d4:status id="3">In Progress</d4:status>
    <d4:status id="4">Resolved</d4:status>
    <d4:status id="5">Closed</d4:status>
    <d4:status id="6">Reopened</d4:status>
  </d4:statuses>
  <d4:resolutions>
    <d4:resolution id="1">Fixed</d4:resolution>
    <d4:resolution id="2">Invalid</d4:resolution>
    <d4:resolution id="3">Wontfix</d4:resolution>
    <d4:resolution id="4">Worksforme</d4:resolution>
  </d4:resolutions>
  <d4:priorities>
    <d4:priority id="1">priority</d4:priority>
    <d4:priority id="2">priority</d4:priority>
    <d4:priority id="3">priority</d4:priority>
    <d4:priority id="4">priority</d4:priority>
  </d4:priorities>
  <d4:types>
    <d4:type id="1">Cosmetic</d4:type>
    <d4:type id="2">Bug</d4:type>
    <d4:type id="3">Feature</d4:type>
    <d4:type id="4">Performance</d4:type>
  </d4:types>
</d4:configuration>
