=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/Project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://www.issuetracker.training.org/project"
	    xmlns:d4="http://www.issuetracker.training.org/project" >

    <element name="projects" type="d4:Projects"/>

    <complexType name="Projects">
    	<sequence>
    		<element name="project" type="d4:Project" maxOccurs="unbounded" minOccurs="1"/>
    	</sequence>
    </complexType>

    <complexType name="Project">
    	<sequence>
    		<element name="name" type="string"/>
    		<element name="description" type="string"/>
    		<element name="userId" type="int"/>
    	</sequence>
    	<attribute name="id" type="int" use="required"/>
    </complexType>


</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/Project.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:projects xmlns:d4="http://www.issuetracker.training.org/project"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.issuetracker.training.org/project project.xsd ">
	<project id="1">
		<name>Visualisation</name>
		<description>Display of graphic objects according to their description</description>
		<userId>1</userId>
	</project>
	<project id="2">
		<name>SectionModel</name>
		<description>Creation of events and states of objects according to their description</description>
		<userId>1</userId>
	</project>
	<project id="3">
		<name>TSPlayer</name>
		<description>play again from impulses</description>
		<userId>1</userId>
	</project>
	<project id="4">
		<name>IS</name>
		<description>receiving data over various communication channels</description>
		<userId>1</userId>
	</project>
</d4:projects>
