=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	    targetNamespace="http://www.issuetracker.training.org/project"
	    xmlns:d4="http://www.issuetracker.training.org/project" >

    <element name="projects" type="d4:Projects"/>

    <complexType name="Projects">
    	<sequence>
    		<element name="project" type="d4:Project" maxOccurs="unbounded" minOccurs="1"/>
    	</sequence>
    </complexType>

    <complexType name="Project">
    	<sequence>
    		<element name="name" type="string"/>
    		<element name="description" type="string"/>
    		<element name="userId" type="int"/>
    		<element name="builds" type="d4:Builds"/>
    	</sequence>
    	<attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="Builds">
    	<sequence>
    		<element name="build" type="d4:Build" maxOccurs="unbounded" minOccurs="1"/>
    	</sequence>
    </complexType>

    <complexType name="Build">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="id" type="string" use="required"/>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== 4ernookiy/issuetracker_dcharnavoki/src/main/resources/xml/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<d4:projects xmlns:d4="http://www.issuetracker.training.org/project"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.issuetracker.training.org/project project.xsd ">
	<project id="0">
		<name>Visualisation</name>
		<description>Display of graphic objects according to their description</description>
		<userId>1</userId>
		<builds>
			<build id="0">3.2.3</build>
			<build id="1">3.2.6</build>
			<build id="2">3.2.7</build>
			<build id="3">3.2.8</build>
		</builds>
	</project>
	<project id="1">
		<name>SectionModel</name>
		<description>Creation of events and states of objects according to their description</description>
		<userId>1</userId>
		<builds>
			<build id="0">2.7.3</build>
			<build id="1">2.7.4</build>
			<build id="2">2.7.5</build>
			<build id="3">2.7.6</build>
			<build id="4">2.7.7</build>
			<build id="5">2.7.8</build>
			<build id="6">2.7.9</build>
		</builds>
	</project>
	<project id="2">
		<name>TSPlayer</name>
		<description>play again from impulses</description>
		<userId>1</userId>
		<builds>
			<build id="0">1.0.3</build>
			<build id="1">1.0.4</build>
			<build id="2">1.0.5</build>
		</builds>
	</project>
	<project id="3">
		<name>IS</name>
		<description>receiving data over various communication channels</description>
		<userId>1</userId>
		<builds>
			<build id="0">1.0.3</build>
			<build id="1">1.0.4</build>
			<build id="2">1.0.5</build>
		</builds>
	</project>
</d4:projects>
